[features]
seeds = false
skip-lint = false
[programs.localnet]
paywall_onchain = "DTsXoYPip9jQTBRvrVXeCWXe3FXbZanBQxgfCm38PE7a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json" # 87AT56xPtYs3yracfWKJ8trTpeahKQY2nTQVSMAsH3J5

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "clones/usdc_clone.json"

[[test.validator.account]]
address = "bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1"
filename = "clones/bsol_clone.json"


